TOOL_NAME   := xdpmon
USER_TARGETS := xdpmon
#XDP_TARGETS := xdpmon_ip_stats_kern xdpmon_port_stats_kern xdpmon_proto_stats_kern
XDP_TARGETS := xdpmon_test_kern

LIB_DIR     = ../lib

include $(LIB_DIR)/common.mk
